/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyDialog {
        "open": boolean;
    }
    interface MyMenu {
        "reset": string;
    }
}
export interface MyDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyDialogElement;
}
export interface MyMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyMenuElement;
}
declare global {
    interface HTMLMyDialogElement extends Components.MyDialog, HTMLStencilElement {
    }
    var HTMLMyDialogElement: {
        prototype: HTMLMyDialogElement;
        new (): HTMLMyDialogElement;
    };
    interface HTMLMyMenuElement extends Components.MyMenu, HTMLStencilElement {
    }
    var HTMLMyMenuElement: {
        prototype: HTMLMyMenuElement;
        new (): HTMLMyMenuElement;
    };
    interface HTMLElementTagNameMap {
        "my-dialog": HTMLMyDialogElement;
        "my-menu": HTMLMyMenuElement;
    }
}
declare namespace LocalJSX {
    interface MyDialog {
        "onOpenChanged"?: (event: MyDialogCustomEvent<any>) => void;
        "open"?: boolean;
    }
    interface MyMenu {
        "onTitleUpdated"?: (event: MyMenuCustomEvent<any>) => void;
        "reset"?: string;
    }
    interface IntrinsicElements {
        "my-dialog": MyDialog;
        "my-menu": MyMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-dialog": LocalJSX.MyDialog & JSXBase.HTMLAttributes<HTMLMyDialogElement>;
            "my-menu": LocalJSX.MyMenu & JSXBase.HTMLAttributes<HTMLMyMenuElement>;
        }
    }
}
